title: Welcome to iitszMeesh
author: Mica Chambers
email: your-email@domain.com
description: Welcome to a site where you can visually see and experience lifestyle change. No one says live was going to be a walk in the park but we God, good faith, ambition and 
the right connections you can live a lifestyle you always wanted and deserved!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
